---
- name: Install {{ sssd_packages }}
  package: name="{{ item }}" state=present
  with_items: "{{ sssd_packages }}"

# No backup in ipa-client-install mode
#- name: Backup {{ sssd_conf }}
#  copy:
#    src: "{{ sssd_conf }}"
#    dest: "{{ sssd_conf }}.bkp"
#    force: no

- name: Template sssd.conf
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    backup: yes
    owner: root
    group: root
    mode: 0600

- name: Enable and start sssd
  service:
    name: sssd
    state: restarted
    enabled: yes
