---
# tasks file for ipaserver

- name: Install - Install IPA server package
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ipaserver_packages }}"

- name: Install - Include Python2/3 import test
  include: "{{role_path}}/tasks/python_2_3_test.yml"
  static: yes

- name: Install - Server installation
  server_install:
    dm_password: "{{ ipaserver_dm_password }}"
    password: "{{ ipaserver_password }}"
    domain: "{{ ipaserver_domain | default(omit)}}"
    realm: "{{ ipaserver_realm | default(omit)}}"
    hostname: "{{ ipaserver_hostname | default(ansible_fqdn) }}"
    setup_dns: "{{ ipaserver_setup_dns }}"
    no_reverse: "{{ ipaserver_no_reverse }}"
    auto_forwarders: "{{ ipaserver_auto_forwarders }}"
  register: server_install

##

- name: Install - Cleanup root IPA cache
  file:
    path: "/root/.ipa_cache"
    state: absent
